[package]
name = "oxirush-sctp"
version = "0.1.0"
edition = "2018"
rust-version = "1.85"
description = "Async SCTP sockets for Tokio on the Linux kernel SCTP stack"
authors = [ "Abhijit Gadgil <gabhijit@iitbombay.org>"]
categories = ["network-programming", "asynchronous"]
keywords = ["sctp", "tokio", "linux", "ngap", "s1ap"]
readme = "README.md"
repository = "https://github.com/linouxis9/oxirush-sctp"
documentation = "https://docs.rs/oxirush-sctp"
license = "Apache-2.0 OR MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
os_socketaddr = { version = "0.2" }
libc = { version = "0.2" }
tokio = { version = "1.32" , features = ["net", "macros", "rt"]}
log = { version = "0.4" }

[dev-dependencies]
tokio = { version = "1.32", features = ["time"] }
